//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace webservices
{
    using System;
    using System.Collections.Generic;
    
    public partial class direccionesweb
    {
        public string diw_cod { get; set; }
        public string diw_dir { get; set; }
        public string diw_des { get; set; }
        public System.DateTime diw_fec { get; set; }
    }
}
